application:
  authentication:
    headers:
    - name: Authorization
      value: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJDc05FMC02T3AwRWZqbUtINldFSVlBalltV1pCakRUeklSellpNE1BME5nIn0.eyJleHAiOjE3NTk5NDU2MzEsImlhdCI6MTc1OTk0NTMzMSwianRpIjoib25ydHJvOjQ5MzA5ZDE2LWVlNjktMjUwNS04NTJhLWYwMWI5Mzk3YjFkMiIsImlzcyI6Imh0dHBzOi8va2V5Y2xvYWstYXV0aG4uYXBwcy5jaTQxOS5hcGljdXJpby10ZXN0aW5nLm9yZy9yZWFsbXMvcmVnaXN0cnkiLCJzdWIiOiJiNTQ3Y2NhYS1jNDJjLTRjYzktYjJiOS02YmNmZjQwZmNkYWMiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJyYXBpZGFzdC1jbGllbnQiLCJzaWQiOiI1ZTQ5NzY2Mi0zMWY2LTk0MzEtODNhMy04OGY4NGEyMDViMjMiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbInNyLWFkbWluIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InJlZ2lzdHJ5LWFkbWluIn0.fx-y32EPYUDwuYxLSn5W0MeeYrXsXTmM5Nu5JCR5NWrdl9k5XkTjqZMLMbPpuwS-xdirszaFR7-ImXGd-vBQTZ-0MclHWZsqujLaLFm-v5VVTkV_x9EvkyEX0ubTGgRh6Yard9tmQiTOJFpQRHq2fKMEG7rmQKB_vKorUxJOa39H870QnV3dVpwjOWxSpgq44COWV6IYORkEThR7MuXJavERSslxp627X5bXN9K1wQS4Hk-D_mMG2X47IY2HDMK-KwliubAXvNg6SRtg9x5Z9RxXgSJ3FqQxe1rqrO7pNZsTIbMsQO2JE8EA6-LspSZTqT5ha87vkO7FLgRRhBoJgw
    type: headers
  shortName: ApicurioRegistry
  url: https://registry-app-authn.apps.ci419.apicurio-testing.org/apis/registry/v3
config:
  configVersion: 5
scanners:
  zap:
    activeScan:
      policy: Kubernetes-API-scan
    apiScan:
      apis:
        apiUrl: https://registry-app-authn.apps.ci419.apicurio-testing.org/api-specifications/registry/v3/openapi.json
    report:
      format:
      - json
      - html
    spider:
      maxDuration: 0
    spiderAjax:
      browserId: firefox-headless
      maxDuration: 0
