application:
  authentication:
    headers:
    - name: Authorization
      value: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ0QnhSMzI5WkpnNDJYV0V4Vy1wNmlrc2d3MjQ5MGNRTS16Z056STZYcDdjIn0.eyJleHAiOjE3NTkwODAyOTAsImlhdCI6MTc1OTA3OTk5MCwianRpIjoib25ydHJvOjYwMGVjYTg2LTliZDMtZjA4MC04YmZlLWM3NWU2MjkwZDZkYiIsImlzcyI6Imh0dHBzOi8va2V5Y2xvYWstYXV0aG4uYXBwcy5jaTQxOS5hcGljdXJpby10ZXN0aW5nLm9yZy9yZWFsbXMvcmVnaXN0cnkiLCJzdWIiOiJjZDViZTUzZi0yYjgzLTRlYjUtYTM3YS01YzcyY2E0ZDNmN2MiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJyYXBpZGFzdC1jbGllbnQiLCJzaWQiOiIyYjk5ZWM3Yy1jZTQwLTQ5MDEtYjQyMC1kYmU4NmEwNWUzOWYiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbInNyLWFkbWluIl19LCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InJlZ2lzdHJ5LWFkbWluIn0.HkJx8DlCtY4sgWhClLA5K2vr1T_HesfwRl_YzA7SY_PS5yl5w1AFkwsT8KD5yVjFnfwpNJdYDMnrrzF9kU6my2dRpcgmq-abLguj7WysapYBw90ZCVXmxWsf2gNNTarj6YgePxRJ1yhnbeOM0wYbsJiJVHa6EeUs-sEIt2voDSqm0YFWEAwcCB0C8bZjUmBdRZGsjVCPzpTPtkxec_3f1xykGd4vqBQ8dm2nd8XDcbAWJw_U4vYrgvaL47uUf-dGz_cMpZRBxmY1tlN6U8MVb0ct4M_v_MHKc521DJ8jgDmHzEzkRd6kyIUCqMwoDiMkOwaNepfOEpbcgT0TlCK9cw
    type: headers
  shortName: ApicurioRegistry
  url: https://registry-app-authn.apps.ci419.apicurio-testing.org/apis/registry/v3
config:
  configVersion: 5
scanners:
  zap:
    activeScan:
      policy: Kubernetes-API-scan
    apiScan:
      apis:
        apiUrl: https://registry-app-authn.apps.ci419.apicurio-testing.org/api-specifications/registry/v3/openapi.json
    report:
      format:
      - json
      - html
    spider:
      maxDuration: 0
    spiderAjax:
      browserId: firefox-headless
      maxDuration: 0
