application:
  authentication:
    headers:
    - name: Authorization
      value: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJlVzVPOGc3N3VJOUZ5Ml9fRHVFTU5VQXhvZWJmZHBpamd0cm9wYWEyUFJVIn0.eyJleHAiOjE3NTUwMjA1MDIsImlhdCI6MTc1NTAyMDIwMiwianRpIjoib25ydHJvOmMwNGVlNTRmLTY3MWUtMDA1OC0xYzkyLTNkYzBhOTA5YjQ5ZCIsImlzcyI6Imh0dHBzOi8va2V5Y2xvYWstYXV0aG4uYXBwcy5jaTQxOS5hcGljdXJpby10ZXN0aW5nLm9yZy9yZWFsbXMvcmVnaXN0cnkiLCJzdWIiOiJjMjVhY2FkZi0yYmNkLTQ5OTMtOTU3OC1kMjUyMWNlZmYwOWUiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJyYXBpZGFzdC1jbGllbnQiLCJzaWQiOiI0YTJlYzVkMy1jZGIzLTRiZGUtOTJhYy1hZjk1MjFjN2RlNTkiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbInNyLWFkbWluIl19LCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InJlZ2lzdHJ5LWFkbWluIn0.hez0rj5gAHB8qB71549zdzDww2yZR8AoGMNeFCyPH1mEV6y_-viZIgkMJFSRchVepPjNYTvNXWaDtEyXiICOjWPcAm9KCQy1Ogu-ByexpboOmfvUvZnHq-4hYC0t6Al0KdU9Umsco5Bi_IMDYGt16yOdGB2m2D2QMB0iwL1vhUaqjonmm5HJfpnzDL0RgD0i-mpgkpoU8UFQ_dAa6rGtZNnGpicQboP0KfBD6yolJIN4hjl3wUzEVx-WZt5ldBN5hJNhTH12--eXXNDv8B4gjwh0l8lYuGvhqdfOeAwzOahthiQVk0L5qVG8brithZzgF-7yT5OeldsrDYOozFyE3g
    type: headers
  shortName: ApicurioRegistry
  url: https://registry-app-authn.apps.ci419.apicurio-testing.org/apis/registry/v2
config:
  configVersion: 5
scanners:
  zap:
    activeScan:
      policy: Kubernetes-API-scan
    apiScan:
      apis:
        apiUrl: https://registry-app-authn.apps.ci419.apicurio-testing.org/api-specifications/registry/v2/openapi.json
    report:
      format:
      - json
      - html
    spider:
      maxDuration: 0
    spiderAjax:
      browserId: firefox-headless
      maxDuration: 0
