application:
  authentication:
    headers:
    - name: Authorization
      value: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ4RHdnX0tySGxvS3VYNld5Q05iZC1RMGpZOTZGZWNnZ1JwbDZ5dGhPUXBZIn0.eyJleHAiOjE3NTQ1OTk0MDgsImlhdCI6MTc1NDU5OTEwOCwianRpIjoib25ydHJvOjg4OTIyMmEyLTQ1OTUtMGY3NC04MWFiLTc3ODc1M2JmMDI2ZiIsImlzcyI6Imh0dHBzOi8va2V5Y2xvYWstYXV0aG4uYXBwcy5jaTQxOS5hcGljdXJpby10ZXN0aW5nLm9yZy9yZWFsbXMvcmVnaXN0cnkiLCJzdWIiOiJiNTYwMDFiNi00OGYxLTQwZTYtOTJkOC1jMzM1OWU1NWY1OGEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJyYXBpZGFzdC1jbGllbnQiLCJzaWQiOiI1NmExN2M5Zi05NzdmLTQwZDUtYmYyNi1hYmQwZGJmYmM2NzgiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbInNyLWFkbWluIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InJlZ2lzdHJ5LWFkbWluIn0.NETkhHY02lbrDx3xHFdFO0aEGnE7rk-1kJ5NFDT5KF7QfVhXpQ4IBcah7_n5YXgIB2o4O7CKSISfe844wXrAukuXBFOfHyoB6494E2O7pnDx533xnwAdgBMbbEUFxjcKazFGZa43ox4nUrbFat4Q2EMdYra5XH_S3NEv5JSD5PPQlddq-pWlU9ndjr0uQbB223m_XYpY7Jea_Q0K2ApR90fvQw_MabInxrywAQ5jejGrNKy2YwqGDz18rBOCAZbGH3jwou7yZ1Hfg6KvoYhetnJZhRYKBjXRfLj3O3kNNrz3KRYm3y02offUenqSIYJUt_JO5Oi4_TR0YMAz0UBckg
    type: headers
  shortName: ApicurioRegistry
  url: https://registry-app-authn.apps.ci419.apicurio-testing.org/apis/registry/v3
config:
  configVersion: 5
scanners:
  zap:
    activeScan:
      policy: Kubernetes-API-scan
    apiScan:
      apis:
        apiUrl: https://registry-app-authn.apps.ci419.apicurio-testing.org/api-specifications/registry/v3/openapi.json
    report:
      format:
      - json
      - html
    spider:
      maxDuration: 0
    spiderAjax:
      browserId: firefox-headless
      maxDuration: 0
