application:
  authentication:
    headers:
    - name: Authorization
      value: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJQOFVMaFhDbjExbnpnekotLWRkandBQ0h2ejhnc1c4Y2drX2ZUWEZtajA0In0.eyJleHAiOjE3NTg1NTk1OTYsImlhdCI6MTc1ODU1OTI5NiwianRpIjoib25ydHJvOmU4N2YxMDg0LTkzOTgtZjEyMC1iZDY4LWY0YmJjMmZiN2E4OSIsImlzcyI6Imh0dHBzOi8va2V5Y2xvYWstYXV0aG4uYXBwcy5jaTQxOS5hcGljdXJpby10ZXN0aW5nLm9yZy9yZWFsbXMvcmVnaXN0cnkiLCJzdWIiOiIxNTE3Y2M2Ny02MTA5LTQwN2QtOTc1My0zY2Y5OTlkY2QzYmQiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJyYXBpZGFzdC1jbGllbnQiLCJzaWQiOiI4OTBjOTM4MS00ZWRjLTQ0ZjctODc4Mi02MGIxZGUwMDJkMjgiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbInNyLWFkbWluIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InJlZ2lzdHJ5LWFkbWluIn0.VnOLTIZeexRp-5eWt8ciGg_aFjmKmioxSuetjQ_EDAwueNcN1P9w4vXXNG0dK8wkLgNuWcaN10xlktdDiNjSBUVAj6r2w12N0EE2ioO3npdPtffXjXQ8elLn2PYHIDSIRWzHajopgcHKmusXxjY3Ajo1buzf1A4SKBey_uTxFHx6ialI2o7fo4v4JcPLKBjYbycYUlO_RAHGlK43Ucu4_G95HsKtKgUdDwt0cdm0YFnSgxfSy_7dhGiJa1eChRaPHxR2T_oqlZdPsweHtUoapBjL7MBnOdp0_nsFsFDvkVME1t1vHoBQIiuaTT1CdaHchcvt_W-mS0qlqdP6g6J9qA
    type: headers
  shortName: ApicurioRegistry
  url: https://registry-app-authn.apps.ci419.apicurio-testing.org/apis/registry/v3
config:
  configVersion: 5
scanners:
  zap:
    activeScan:
      policy: Kubernetes-API-scan
    apiScan:
      apis:
        apiUrl: https://registry-app-authn.apps.ci419.apicurio-testing.org/api-specifications/registry/v3/openapi.json
    report:
      format:
      - json
      - html
    spider:
      maxDuration: 0
    spiderAjax:
      browserId: firefox-headless
      maxDuration: 0
