application:
  authentication:
    headers:
    - name: Authorization
      value: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJrUHRmd0pCeF9zQmcyalVMeWlWdlRpdUFlNWppTURjX29CcGo5V05vTTRFIn0.eyJleHAiOjE3NjA1MzY3MDksImlhdCI6MTc2MDUzNjQwOSwianRpIjoib25ydHJvOjZhMDRmMmI5LTRjNzItNzUyNS05MjVlLWU3OWQwNThhNDdjMyIsImlzcyI6Imh0dHBzOi8va2V5Y2xvYWstYXV0aG4uYXBwcy5jaTQxOS5hcGljdXJpby10ZXN0aW5nLm9yZy9yZWFsbXMvcmVnaXN0cnkiLCJzdWIiOiJlOGQ4MzM0OC1iZmY2LTQyOGMtOTM5My0wNGUwYzhhNDVhNzEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJyYXBpZGFzdC1jbGllbnQiLCJzaWQiOiJjMjMzYmQ1ZS1hZDU2LWZmMzAtMWRkNC04NGYzYmRhNWI1NTAiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbInNyLWFkbWluIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InJlZ2lzdHJ5LWFkbWluIn0.XJSyFTetPCl_lo7_OQtwIcXQBbjQ5EbSHR5NMKKtF-RfIfy_9EJGgT-1sL7RDqxUlkYG0RIqiE0n5mWggoRUEj8yrIWeT1aM6XpOfydYSD6jtlad2FjpJorA552qlVernRrxEzCDBLQ_dfVk0itb3qGpwfHkdWattacHbVoRtjs_OSEnM9mjfCUN9DdYEYNDZItdjUYJpfQ3Sh5KSrCgNJFn48Vcv7O2B613lQtN58yOMSzqLtVjifUyJvWR7HtPn053kCNXCgBGPIraG6qUqQkPOrBeiR0qGLyJtxKdgwLkHPkT-28SAL3ueApbYk8bsCgzDluUTr5qa3FxEQ-fRg
    type: headers
  shortName: ApicurioRegistry
  url: https://registry-app-authn.apps.ci419.apicurio-testing.org/apis/registry/v3
config:
  configVersion: 5
scanners:
  zap:
    activeScan:
      policy: Kubernetes-API-scan
    apiScan:
      apis:
        apiUrl: https://registry-app-authn.apps.ci419.apicurio-testing.org/api-specifications/registry/v3/openapi.json
    report:
      format:
      - json
      - html
    spider:
      maxDuration: 0
    spiderAjax:
      browserId: firefox-headless
      maxDuration: 0
