application:
  authentication:
    headers:
    - name: Authorization
      value: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJfUnZZRF83MUItWGxuOWdiaGpkLUctQnF5blQ4VlgyVlJxRmxyTlhFc0hVIn0.eyJleHAiOjE3NTk5MzAxNTMsImlhdCI6MTc1OTkyOTg1MywianRpIjoib25ydHJvOmE1NzE0N2FhLTUxNmEtMDY0ZS1lZmY3LWE2NzYxOTNlYjhmMiIsImlzcyI6Imh0dHBzOi8va2V5Y2xvYWstYXV0aG4uYXBwcy5jaTQxOS5hcGljdXJpby10ZXN0aW5nLm9yZy9yZWFsbXMvcmVnaXN0cnkiLCJzdWIiOiI4NmJkNjVjMi04MTM4LTRlYjItOGYyYS00NmUwZjAwNTY1MzUiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJyYXBpZGFzdC1jbGllbnQiLCJzaWQiOiI3Mzg1MjIxNC1iNWU3LTJlZDgtNzM2Yy1lNDdmYmFlNGE4MmMiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbInNyLWFkbWluIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InJlZ2lzdHJ5LWFkbWluIn0.Gs1bQizHkatQ2-EGL5YM_xmnGptlzGXT5wFu7u8kuJyauDW47g74QK5F1-jkEFQ03mC3-NSRZiLHuKax9xf5HipW-dZEaDRqsZYYpug3Pq_qNMoC-BQmVFV2k3YE7PhYMhwL5FfRiw7WBXf245UotRIEzKf1Z4LYIGkzjiZYJn6wbXJMjjZ17P3-2gUPPE4SnZdsfs3UiP0MJ4sjcIhBUsUc9PLctK7oFFQL5LyD4seFrYtvLYZvfk4Gvh01-68Jd5cnv9DxD9-Bo0-4SrW3nXhKEzfLi4SmoM1Un1Sz1l3D3AcKYyBKbKRhqj-MVbAlbNP9KZl1sPUfgFjHcVrMTw
    type: headers
  shortName: ApicurioRegistry
  url: https://registry-app-authn.apps.ci419.apicurio-testing.org/apis/registry/v3
config:
  configVersion: 5
scanners:
  zap:
    activeScan:
      policy: Kubernetes-API-scan
    apiScan:
      apis:
        apiUrl: https://registry-app-authn.apps.ci419.apicurio-testing.org/api-specifications/registry/v3/openapi.json
    report:
      format:
      - json
      - html
    spider:
      maxDuration: 0
    spiderAjax:
      browserId: firefox-headless
      maxDuration: 0
