application:
  authentication:
    headers:
    - name: Authorization
      value: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ0d0lxaVdCNU1RMEp6RlpKSmNBR1ZvSFg2VE9fOWttM2luYjFZTVV2ZHVFIn0.eyJleHAiOjE3NTg5MTA1NDUsImlhdCI6MTc1ODkxMDI0NSwianRpIjoib25ydHJvOjFhMmRkMjA0LTIyODktMDJkMS00NmRhLThjYTlkYTA0NDkxNiIsImlzcyI6Imh0dHBzOi8va2V5Y2xvYWstYXV0aG4uYXBwcy5jaTQxOS5hcGljdXJpby10ZXN0aW5nLm9yZy9yZWFsbXMvcmVnaXN0cnkiLCJzdWIiOiI5M2UxM2UyNC01Njg1LTQyM2YtYTU4Yy03NmQyZDU0NDdmMjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJyYXBpZGFzdC1jbGllbnQiLCJzaWQiOiIzZTY3ZDgxOS1kZmVjLTRmNDMtODNiMy1mYzcyOWI4YTAxNmQiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbInNyLWFkbWluIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InJlZ2lzdHJ5LWFkbWluIn0.ltlirpIMN2F66QesrEaI64GzJuIG9stxt97s4WQXZPMms-KiQGwYTsTlhRO6NFsNAYbtASuzZGQxIvAS8Xc0KiAhIXNM1GO7QKgTWoSDHteaOZLkF_zudaIeUqPTb5MtDhoNvBVJmPV3zKSMZiqC4o94Q-FLHst8zeV0YZk8o3vJzY3i9IPRqsv2gWyq8ywJK6g4eaY1PFiBepCyu20zF2xOhfOcyeajf11DTATfSFCtTo4MDcFjj-liXG_1mJycFVw8Stg7FGu875mQBTqplsegL4vOfpJIStY9csYaqeHKxwMTs3scudYFiSrKErtgM9BMdOBUs0ZIAFCaKAAgXw
    type: headers
  shortName: ApicurioRegistry
  url: https://registry-app-authn.apps.ci419.apicurio-testing.org/apis/registry/v3
config:
  configVersion: 5
scanners:
  zap:
    activeScan:
      policy: Kubernetes-API-scan
    apiScan:
      apis:
        apiUrl: https://registry-app-authn.apps.ci419.apicurio-testing.org/api-specifications/registry/v3/openapi.json
    report:
      format:
      - json
      - html
    spider:
      maxDuration: 0
    spiderAjax:
      browserId: firefox-headless
      maxDuration: 0
